class MarkdownRendererApp {
    static MIN_HISTORY_CONTENT_LENGTH = 10;

    constructor() {
        /** @type {AppDOM} */
        this.dom = {};
        this.savedSectionsManager = null;
        this.currentContentManager = new CurrentContentManager();
        this.stateStore = new UIStateStore();
        this.markedLoader = new MarkedLoader();
        this.a11y = null;
        this.init();
    }

    init() {
        document.addEventListener('DOMContentLoaded', () => {
            this.dom = UIDomRegistry.collect();
            this.a11y = new AccessibilityController(this.dom);
            this.a11y.init();

            this.bindStateSync();
            this.bindEventListeners();
            this.initCurrentContentManager();
            this.initializeSavedSectionsManager();
            this.setupMarked();
        });
    }

    initializeSavedSectionsManager() {
        const initialize = () => {
            try {
                this.savedSectionsManager = new SavedSectionsManager(this.dom, this);
            } catch (error) {
                console.error('Failed to initialize SavedSectionsManager', error);
                this.stateStore.setState({ lastError: 'Failed to initialize library manager.' });
            }
        };

        if ('requestIdleCallback' in window) {
            window.requestIdleCallback(initialize, { timeout: 500 });
            return;
        }

        setTimeout(initialize, 0);
    }

    bindStateSync() {
        this.stateStore.subscribe((state) => {
            const isBusy = state.isRendering;
            if (this.dom.renderButton) {
                this.dom.renderButton.disabled = isBusy;
                this.dom.renderButton.setAttribute('aria-busy', String(isBusy));
            }
            if (this.dom.pasteAndRenderButton) {
                this.dom.pasteAndRenderButton.disabled = isBusy;
            }
            if (this.dom.markdownInput) {
                this.dom.markdownInput.setAttribute('data-has-content', String(state.inputLength > 0));
            }
        });
    }

    bindEventListeners() {
        this.dom.renderButton?.addEventListener('click', () => {
            this.handleRender();
        });

        this.dom.pasteAndRenderButton?.addEventListener('click', () => {
            this.handlePasteAndRender();
        });

        this.dom.clearButton?.addEventListener('click', () => {
            this.handleClear();
        });

        this.dom.importBtn?.addEventListener('click', () => {
            this.dom.importFileInput?.click();
        });

        this.dom.markdownInput?.addEventListener('keydown', (event) => {
            if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') {
                event.preventDefault();
                this.handleRender();
            }
        });

        this.dom.markdownInput?.addEventListener('input', (event) => {
            const value = event.target instanceof HTMLTextAreaElement ? event.target.value : '';
            this.stateStore.setState({ inputLength: value.length });
        });
    }

    initCurrentContentManager() {
        if (!this.dom.markdownInput) return;

        this.currentContentManager.restoreContent(this.dom.markdownInput);
        this.currentContentManager.setupAutoSave(this.dom.markdownInput);
        this.stateStore.setState({ inputLength: this.dom.markdownInput.value.length });
    }

    async setupMarked() {
        const markedReady = await this.markedLoader.ensureAvailable();
        const isConfigured = markedReady && this.markedLoader.configure();
        this.updateRenderButtonsAvailability(isConfigured);

        if (!isConfigured) {
            console.error('Marked.js is unavailable - fallback mode enabled');
        }
    }

    updateRenderButtonsAvailability(isConfigured) {
        if (this.dom.renderButton) {
            this.dom.renderButton.disabled = false;
            this.dom.renderButton.title = isConfigured
                ? 'Render the markdown content'
                : 'Render the markdown content (using fallback renderer)';
        }

        if (this.dom.pasteAndRenderButton) {
            this.dom.pasteAndRenderButton.disabled = false;
            this.dom.pasteAndRenderButton.title = isConfigured
                ? 'Paste from clipboard and render'
                : 'Paste from clipboard and render (using fallback renderer)';
        }
    }

    getInputValue() {
        return this.dom.markdownInput?.value ?? '';
    }

    setInputValue(value) {
        if (!this.dom.markdownInput) return;
        this.dom.markdownInput.value = value;
        this.stateStore.setState({ inputLength: value.length });
    }

    createHistoryItem(markdownText) {
        return {
            id: `temp_${Date.now()}`,
            title: this.extractTitle(markdownText) || 'Untitled',
            content: markdownText,
            viewedAt: new Date().toISOString(),
            titleAutoGenerated: true
        };
    }

    async handleRender(skipHistoryUpdate = false) {
        const markdownText = this.getInputValue();
        if (!markdownText.trim()) {
            await CustomModal.alert('Please enter some markdown content to render.');
            return;
        }

        if (!skipHistoryUpdate && markdownText.trim().length > MarkdownRendererApp.MIN_HISTORY_CONTENT_LENGTH) {
            this.savedSectionsManager?.addToHistory(this.createHistoryItem(markdownText));
        }

        this.stateStore.setState({ isRendering: true, lastError: null });
        this.a11y?.announce('Rendering markdown in a new tab');

        try {
            await this.renderMarkdown(markdownText);
        } catch (error) {
            await this.handleRenderError(error);
        } finally {
            this.stateStore.setState({ isRendering: false });
        }
    }

    async handleRenderError(error) {
        console.error('Error during markdown rendering:', error);
        const message = error instanceof Error && error.message.includes('marked')
            ? 'The Markdown library failed to load properly. Please refresh the page and ensure you have an internet connection.'
            : 'An error occurred while rendering the markdown. Please check the console for details.';

        this.stateStore.setState({ lastError: message });
        await CustomModal.alert(message);
    }

    extractTitle(content) {
        const lines = content.split('\n');
        for (const line of lines) {
            const trimmed = line.trim();
            if (trimmed.startsWith('# ')) return trimmed.slice(2).trim();
            if (trimmed.startsWith('## ')) return trimmed.slice(3).trim();
            if (trimmed && !trimmed.startsWith('#') && trimmed.length < 100) return trimmed;
        }
        return null;
    }

    async handlePasteAndRender() {
        if (!navigator.clipboard?.readText) {
            await CustomModal.alert('Clipboard API not available. Please use a modern browser or check permissions.');
            return;
        }

        try {
            const text = await navigator.clipboard.readText();
            this.setInputValue(text);
            this.currentContentManager.saveCurrentContent(text);
            await this.handleRender();
        } catch (error) {
            console.error('Failed to read clipboard:', error);
            await CustomModal.alert('Failed to read from clipboard. Please check permissions or paste manually.');
        }
    }

    async handleClear() {
        if (this.getInputValue()) {
            const confirmed = await CustomModal.confirm('Are you sure you want to clear the input?', 'Clear Content');
            if (!confirmed) return;
        }

        this.setInputValue('');
        this.dom.markdownInput?.focus();
        this.currentContentManager.clearCurrentContent();
        this.a11y?.announce('Markdown input cleared');
    }

    async renderMarkdown(markdownText) {
        const markedAvailable = await this.markedLoader.ensureAvailable();
        const canUseMarked = markedAvailable && this.markedLoader.configure();

        if (!canUseMarked) {
            this.stateStore.setState({ renderMode: 'fallback' });
            await this.renderWithFallback(markdownText);
            return;
        }

        this.stateStore.setState({ renderMode: 'full' });
        const { tempText, mathExpressions } = MathProcessor.preserveMathExpressions(markdownText);
        let html = marked.parse(tempText);
        html = MathProcessor.restoreMathExpressions(html, mathExpressions);
        const { nested: listItems, flat: flatListItems } = ListItemParser.parseAll(markdownText);
        const fullPageHtml = RenderedPageBuilder.build(
            html,
            markdownText,
            'Rendered Markdown & LaTeX',
            listItems,
            flatListItems
        );
        await this.openInNewTab(fullPageHtml);
    }

    async renderWithFallback(markdownText) {
        if (!this.markedLoader.fallbackWarningLogged) {
            await CustomModal.alert('The Markdown library failed to load due to network restrictions. Using basic fallback renderer with limited features. For full functionality, please refresh the page with a stable internet connection.');
            this.markedLoader.fallbackWarningLogged = true;
        }

        const basicHtml = FallbackRenderer.renderToHtml(markdownText);
        const { nested: listItems, flat: flatListItems } = ListItemParser.parseAll(markdownText);
        const fullPageHtml = RenderedPageBuilder.build(
            basicHtml,
            markdownText,
            'Rendered Markdown & LaTeX (Basic Mode)',
            listItems,
            flatListItems
        );
        await this.openInNewTab(fullPageHtml);
    }

    async openInNewTab(htmlContent) {
        let blobUrl = null;

        try {
            blobUrl = URL.createObjectURL(new Blob([htmlContent], { type: 'text/html' }));
            const newTab = window.open(blobUrl, '_blank', 'noopener,noreferrer');

            if (!newTab) {
                throw new Error('Popup blocked');
            }

            newTab.focus();
            setTimeout(() => {
                if (blobUrl) URL.revokeObjectURL(blobUrl);
            }, 60_000);
        } catch (error) {
            if (blobUrl) URL.revokeObjectURL(blobUrl);
            console.error('Error creating/opening blob URL:', error);

            const fallbackTab = window.open('', '_blank', 'noopener,noreferrer');
            if (fallbackTab) {
                fallbackTab.document.open();
                fallbackTab.document.write(htmlContent);
                fallbackTab.document.close();
                fallbackTab.focus();
                return;
            }

            await CustomModal.alert('Failed to open new tab. Please check your pop-up blocker settings.');
        }
    }
}
