class HistoryManager {
    constructor() {
        this.STORAGE_KEY = 'markdownHistory';
        this.MAX_HISTORY_ITEMS = 5;
    }
    
    addToHistory(section) {
        const history = this.getHistory();
        const existingIndex = history.findIndex(item => item.content === section.content);
        
        let updatedHistory;
        if (existingIndex !== -1) {
            var existingItem = history[existingIndex];
            updatedHistory = [];
            for (var i = 0; i < history.length; i++) {
                if (i !== existingIndex) updatedHistory.push(history[i]);
            }
            updatedHistory.unshift({
                id: existingItem.id,
                title: existingItem.title,
                content: existingItem.content,
                viewedAt: new Date().toISOString(),
                titleAutoGenerated: existingItem.titleAutoGenerated
            });
        } else {
            updatedHistory = [];
            for (var j = 0; j < history.length; j++) {
                if (history[j].id !== section.id) updatedHistory.push(history[j]);
            }
            
            const uniqueTitle = this.generateUniqueTitle(section.title, updatedHistory);
            
            updatedHistory.unshift({
                id: section.id,
                title: uniqueTitle,
                content: section.content,
                viewedAt: new Date().toISOString(),
                titleAutoGenerated: section.titleAutoGenerated
            });
        }
        
        if (updatedHistory.length > 1) {
            updatedHistory = this.resolveTitleConflicts(updatedHistory);
        }
        
        this.setHistory(updatedHistory.slice(0, this.MAX_HISTORY_ITEMS));
    }
    
    getHistory() {
        try {
            return JSON.parse(localStorage.getItem(this.STORAGE_KEY) || '[]');
        } catch (e) {
            console.error('Error loading history:', e);
            return [];
        }
    }
    
    setHistory(history) {
        try {
            localStorage.setItem(this.STORAGE_KEY, JSON.stringify(history));
        } catch (e) {
            console.error('Error saving history:', e);
        }
    }
    
    clearHistory() {
        localStorage.removeItem(this.STORAGE_KEY);
    }
    
    generateUniqueTitle(originalTitle, existingHistory) {
        var hasConflict = false;
        for (var k = 0; k < existingHistory.length; k++) {
            if (existingHistory[k].title === originalTitle) { hasConflict = true; break; }
        }
        if (!hasConflict) return originalTitle;
        var suffix = this.generateContentBasedSuffix(null, existingHistory.filter(function(item) {
            return item.title === originalTitle || item.title.indexOf(originalTitle + ' (') === 0;
        }));
        return originalTitle + ' (' + suffix + ')';
    }
    
    resolveTitleConflicts(history) {
        if (history.length < 2) return history;
        var updatedHistory = history.slice();
        var titleGroups = {};
        var hasMultiples = false;
        
        for (var m = 0; m < updatedHistory.length; m++) {
            var item = updatedHistory[m];
            var baseTitle = this.extractBaseTitle(item.title);
            if (!titleGroups[baseTitle]) {
                titleGroups[baseTitle] = [];
            }
            titleGroups[baseTitle].push({ item: item, index: m });
            if (titleGroups[baseTitle].length > 1) hasMultiples = true;
        }
        
        if (!hasMultiples) return updatedHistory;
        
        var groups = Object.values(titleGroups);
        for (var g = 0; g < groups.length; g++) {
            var group = groups[g];
            if (group.length < 2) continue;
            group.sort(function(a, b) { return new Date(b.item.viewedAt) - new Date(a.item.viewedAt); });
            
            for (var t = 0; t < group.length; t++) {
                var entry = group[t];
                if (t === 0) {
                    updatedHistory[entry.index].title = this.extractBaseTitle(entry.item.title);
                } else {
                    var otherItems = [];
                    for (var o = 0; o < t; o++) otherItems.push(group[o].item);
                    var suffix = this.generateContentBasedSuffix(entry.item.content, otherItems);
                    updatedHistory[entry.index].title = this.extractBaseTitle(entry.item.title) + ' (' + suffix + ')';
                }
            }
        }
        
        return updatedHistory;
    }
    
    extractBaseTitle(title) {
        var match = title.match(/^(.+?)\s*\(/);
        return match ? match[1].trim() : title;
    }
    
    generateContentBasedSuffix(content, conflictingItems) {
        if (!conflictingItems || conflictingItems.length === 0) {
            return content ? content.trim().substring(0, 25) : 'content';
        }
        var result = this.findDistinctiveHeader(content, conflictingItems);
        if (result) return this.truncateText(result, 25);
        result = this.findDistinctiveLine(content, conflictingItems);
        if (result) return this.truncateText(result, 25);
        return (content ? content.trim().length : 0) + ' chars';
    }
    
    findDistinctiveHeader(content, conflictingItems) {
        var headers = this.extractHeaders(content);
        if (headers.length <= 1) return null;
        for (var h = 0; h < headers.length; h++) {
            var header = headers[h];
            var distinct = true;
            for (var c = 0; c < conflictingItems.length; c++) {
                if (this.extractHeaders(conflictingItems[c].content).indexOf(header) !== -1) {
                    distinct = false;
                    break;
                }
            }
            if (distinct) return header;
        }
        return null;
    }
    
    findDistinctiveLine(content, conflictingItems) {
        var contentLines = this.extractContentLines(content);
        for (var cl = 0; cl < contentLines.length; cl++) {
            var line = contentLines[cl];
            var distinct = true;
            for (var ci = 0; ci < conflictingItems.length; ci++) {
                if (this.extractContentLines(conflictingItems[ci].content).indexOf(line) !== -1) {
                    distinct = false;
                    break;
                }
            }
            if (distinct) return line;
        }
        return null;
    }
    
    extractHeaders(content) {
        var headers = [];
        var lines = content.split('\n');
        for (var i = 0; i < lines.length; i++) {
            var trimmed = lines[i].trim();
            if (trimmed.charAt(0) === '#') {
                var match = trimmed.match(/^#{1,6}\s+(.+)$/);
                if (match) headers.push(match[1].trim());
            }
        }
        return headers;
    }
    
    extractContentLines(content) {
        var lines = content.split('\n');
        var contentLines = [];
        for (var i = 0; i < lines.length; i++) {
            var trimmed = lines[i].trim();
            if (trimmed && trimmed.charAt(0) !== '#' && trimmed.indexOf('```') !== 0 && trimmed.length > 5) {
                contentLines.push(trimmed);
                if (contentLines.length >= 3) break;
            }
        }
        return contentLines;
    }
    
    truncateText(text, maxLength) {
        if (text.length <= maxLength) return text;
        return text.substring(0, maxLength - 3) + '...';
    }
}