class HistoryManager {
    constructor() {
        this.STORAGE_KEY = 'markdownHistory';
        this.MAX_HISTORY_ITEMS = 5;
    }
    
    addToHistory(section) {
        const history = this.getHistory();
        const existingIndex = history.findIndex(item => item.content === section.content);
        
        let updatedHistory;
        if (existingIndex !== -1) {
            const existingItem = history[existingIndex];
            updatedHistory = [];
            for (let i = 0; i < history.length; i++) {
                if (i !== existingIndex) updatedHistory.push(history[i]);
            }
            updatedHistory.unshift({
                id: existingItem.id,
                title: existingItem.title,
                content: existingItem.content,
                viewedAt: new Date().toISOString(),
                titleAutoGenerated: existingItem.titleAutoGenerated
            });
        } else {
            updatedHistory = [];
            for (let j = 0; j < history.length; j++) {
                if (history[j].id !== section.id) updatedHistory.push(history[j]);
            }
            
            const uniqueTitle = this.generateUniqueTitle(section.title, section.content, updatedHistory);
            
            updatedHistory.unshift({
                id: section.id,
                title: uniqueTitle,
                content: section.content,
                viewedAt: new Date().toISOString(),
                titleAutoGenerated: section.titleAutoGenerated
            });
        }
        
        if (updatedHistory.length > 1) {
            updatedHistory = this.resolveTitleConflicts(updatedHistory);
        }
        
        this.setHistory(updatedHistory.slice(0, this.MAX_HISTORY_ITEMS));
    }
    
    getHistory() {
        try {
            return JSON.parse(localStorage.getItem(this.STORAGE_KEY) || '[]');
        } catch (e) {
            console.error('Error loading history:', e);
            return [];
        }
    }
    
    setHistory(history) {
        try {
            localStorage.setItem(this.STORAGE_KEY, JSON.stringify(history));
        } catch (e) {
            console.error('Error saving history:', e);
        }
    }
    
    clearHistory() {
        localStorage.removeItem(this.STORAGE_KEY);
    }
    
    generateUniqueTitle(originalTitle, content, existingHistory) {
        let hasConflict = false;
        for (let k = 0; k < existingHistory.length; k++) {
            if (existingHistory[k].title === originalTitle) { hasConflict = true; break; }
        }
        if (!hasConflict) return originalTitle;
        const suffix = this.generateContentBasedSuffix(content, existingHistory.filter(function(item) {
            return item.title === originalTitle || item.title.indexOf(originalTitle + ' (') === 0;
        }));
        return originalTitle + ' (' + suffix + ')';
    }
    
    resolveTitleConflicts(history) {
        if (history.length < 2) return history;
        const updatedHistory = history.slice();
        const titleGroups = {};
        let hasMultiples = false;
        
        for (let m = 0; m < updatedHistory.length; m++) {
            const item = updatedHistory[m];
            const baseTitle = this.extractBaseTitle(item.title);
            if (!titleGroups[baseTitle]) {
                titleGroups[baseTitle] = [];
            }
            titleGroups[baseTitle].push({ item: item, index: m });
            if (titleGroups[baseTitle].length > 1) hasMultiples = true;
        }
        
        if (!hasMultiples) return updatedHistory;
        
        const groups = Object.values(titleGroups);
        for (let g = 0; g < groups.length; g++) {
            const group = groups[g];
            if (group.length < 2) continue;
            group.sort(function(a, b) { return new Date(b.item.viewedAt) - new Date(a.item.viewedAt); });
            
            for (let t = 0; t < group.length; t++) {
                const entry = group[t];
                if (t === 0) {
                    updatedHistory[entry.index].title = this.extractBaseTitle(entry.item.title);
                } else {
                    const otherItems = [];
                    for (let o = 0; o < t; o++) otherItems.push(group[o].item);
                    const suffix = this.generateContentBasedSuffix(entry.item.content, otherItems);
                    updatedHistory[entry.index].title = this.extractBaseTitle(entry.item.title) + ' (' + suffix + ')';
                }
            }
        }
        
        return updatedHistory;
    }
    
    extractBaseTitle(title) {
        const match = title.match(/^(.+?)\s*\(/);
        return match ? match[1].trim() : title;
    }
    
    generateContentBasedSuffix(content, conflictingItems) {
        if (!conflictingItems || conflictingItems.length === 0) {
            return content ? content.trim().substring(0, 25) : 'content';
        }
        let result = this.findDistinctiveHeader(content, conflictingItems);
        if (result) return this.truncateText(result, 25);
        result = this.findDistinctiveLine(content, conflictingItems);
        if (result) return this.truncateText(result, 25);
        return (content ? content.trim().length : 0) + ' chars';
    }
    
    findDistinctiveHeader(content, conflictingItems) {
        const headers = this.extractHeaders(content);
        if (headers.length <= 1) return null;

        const conflictingHeaders = new Set();
        for (let c = 0; c < conflictingItems.length; c++) {
            const extHeaders = this.extractHeaders(conflictingItems[c].content);
            for (let i = 0; i < extHeaders.length; i++) {
                conflictingHeaders.add(extHeaders[i]);
            }
        }

        for (let h = 0; h < headers.length; h++) {
            const header = headers[h];
            if (!conflictingHeaders.has(header)) {
                return header;
            }
        }
        return null;
    }
    
    findDistinctiveLine(content, conflictingItems) {
        const contentLines = this.extractContentLines(content);

        const conflictingLines = new Set();
        for (let ci = 0; ci < conflictingItems.length; ci++) {
            const extLines = this.extractContentLines(conflictingItems[ci].content);
            for (let i = 0; i < extLines.length; i++) {
                conflictingLines.add(extLines[i]);
            }
        }

        for (let cl = 0; cl < contentLines.length; cl++) {
            const line = contentLines[cl];
            if (!conflictingLines.has(line)) {
                return line;
            }
        }
        return null;
    }
    
    extractHeaders(content) {
        if (!content) return [];
        const headers = [];
        const lines = content.split('\n');
        for (let i = 0; i < lines.length; i++) {
            const trimmed = lines[i].trim();
            if (trimmed.charAt(0) === '#') {
                const match = trimmed.match(/^#{1,6}\s+(.+)$/);
                if (match) headers.push(match[1].trim());
            }
        }
        return headers;
    }
    
    extractContentLines(content) {
        if (!content) return [];
        const lines = content.split('\n');
        const contentLines = [];
        for (let i = 0; i < lines.length; i++) {
            const trimmed = lines[i].trim();
            if (trimmed && trimmed.charAt(0) !== '#' && trimmed.indexOf('```') !== 0 && trimmed.length > 5) {
                contentLines.push(trimmed);
                if (contentLines.length >= 3) break;
            }
        }
        return contentLines;
    }
    
    truncateText(text, maxLength) {
        if (text.length <= maxLength) return text;
        return text.substring(0, maxLength - 3) + '...';
    }
}